CC=g++-11
test: test.cpp
	$(CC) test.cpp -o test
	./test

test2: test2.cpp
	$(CC) test2.cpp -o test2
	./test2

test3: test3.cpp
	$(CC) test3.cpp -o test3
	./test3

test4: test4.cpp
	$(CC) test4.cpp -o test4
	./test4
